parameters:
  current_stage: 'dev'
  dependsOn: 'Build'
  WebAppName: 'tailspin-space-game-web-dev-17587'
  resourceManager: 'sc-all'
  slotBool: false
  slotName: 'rc'

stages:
- stage: '${{ parameters.current_stage }}'
  displayName: 'Deploy to the ${{ parameters.current_stage }} environment'
  dependsOn: '${{ parameters.dependsOn }}'
  jobs:
  - deployment: '${{ parameters.current_stage }}'
    pool:
      vmImage: 'ubuntu-16.04'
    environment: '${{ parameters.current_stage }}'
    variables:
    - template: "vars.yml"
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website'
            inputs:
              azureSubscription: '${{ parameters.resourceManager }}'
              appType: 'webApp'
              appName: '${{ parameters.WebAppName }}'
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'
              ${{ if eq(parameters.slotBool, 'true') }}:
                deployToSlotOrASE: '${{ parameters.slotBool }}'
                SlotName: '${{ parameters.current_stage }}'